# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Random, Cloudy, DevOpsy Stuff"
description: "A collection of things related to cloud devops and things I think are interesting"
avatar: images/bitmoji.png
email: info@indigo-tangerine.nl
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://indigo-tangerine.nl" # the base hostname & protocol for your site, e.g. http://example.com
domain: indigo-tangerine.github.io
github_username: indigo-tangerine

# Build settings
theme: minima
minima:
  skin: dark
  date_format: "%d %B %Y"
  social_links:
    linkedin: rupertbroad
    github: indigo-tangerine/indigo-tangerine.github.io
show_excerpts: true
plugins:
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-paginate # Adding pagination capability
  - jekyll-sitemap
  - jekyll-seo-tag

google_analytics: UA-161773166-1

paginate: 8
paginate_path: "/blog/page:num"

categories:
  type: liquid
  path: /categories/
tags:
  type: liquid
  path: /tags/

collections:
  projects:
    output: true
    permalink: /:collection/:title

github_comments_repository: indigo-tangerine/indigo-tangerine-github-io-comments
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
